image: node:latest

before_script:
  - npm i -g firebase-tools

deploy-hosting:
  stage: deploy
  before_script:
    - echo "$FIREBASE_CONFIG" > src/.firebaseConfig.ts
    - echo "$FEATURE_FLAGS_CONFIG" > src/.featureFlagsConfig.ts
  script:
    - npm i
    - npm run build
    - firebase deploy --only hosting --token $FIREBASE_TOKEN
  only:
    - master
  environment:
    name: production
    url: https://thestablemanager.com
